const LOCALES = {
  "id": { "name": "Bahasa Indonesia", "flag": "id" },
  "en": { "name": "English", "flag": "gb" },
  "ja": { "name": "日本語", "flag": "jp" },
  "ar": { "name": "العربية", "flag": "sa", "rtl": true },
  "zh": { "name": "中文", "flag": "cn" }
};

const LANG = {
  "id": {
    "nav.services": "Layanan",
    "nav.addons": "Layanan Tambahan",
    "nav.process": "Proses",
    "nav.contact": "Kontak",

    "hero.badge": "Freelance Web Developer · Indonesia",
    "hero.title": "Website & Aplikasi Web yang Siap Menghasilkan",
    "hero.subtitle": "Spesialis WordPress, WooCommerce, Elementor, dan aplikasi web custom dengan Laravel & CodeIgniter. Dari toko online sampai sistem internal bisnis.",
    "hero.scroll": "Gulir ke bawah",

    "services.title": "Layanan",
    "services.subtitle": "Apa yang bisa saya kerjakan untuk bisnis Anda",
    "services.1.title": "Toko Online WooCommerce",
    "services.1.desc": "Toko online lengkap dengan katalog produk, keranjang, payment gateway (Midtrans/Xendit/Stripe), dan pengaturan ongkir.",
    "services.2.title": "Custom WordPress Plugin",
    "services.2.desc": "Plugin khusus sesuai kebutuhan: integrasi API, fitur custom WooCommerce, otomasi, dan dashboard admin.",
    "services.3.title": "Desain Elementor",
    "services.3.desc": "Landing page dan website company profile berbasis Elementor, cepat, responsif, dan mudah Anda edit sendiri.",
    "services.4.title": "Aplikasi Web Laravel",
    "services.4.desc": "Sistem custom: CRM, booking, inventory, POS, atau REST API untuk aplikasi mobile Anda.",
    "services.5.title": "Aplikasi Web CodeIgniter",
    "services.5.desc": "Pengembangan baru atau maintenance aplikasi CodeIgniter 3/4 yang sudah berjalan.",
    "services.6.title": "Maintenance & Perbaikan",
    "services.6.desc": "Perbaikan error, optimasi kecepatan, keamanan, migrasi hosting, dan update rutin.",

    "addons.title": "Layanan Tambahan",
    "addons.subtitle": "Pekerjaan berskala kecil yang bisa dipesan satuan, tanpa paket besar",
    "addons.1.title": "Website Tweaks",
    "addons.1.desc": "Perubahan kecil pada layout, warna, teks, atau CSS yang bandel. Dihitung per item dan biasanya selesai di hari yang sama.",
    "addons.2.title": "Kustomisasi Tema & Plugin",
    "addons.2.desc": "Modifikasi tema atau plugin yang sudah Anda pakai agar berperilaku sesuai kebutuhan, tanpa bikin update berikutnya rusak.",
    "addons.3.title": "PSD / Figma ke HTML",
    "addons.3.desc": "Konversi file desain jadi HTML/CSS responsif yang rapi, presisi, dan siap dilanjutkan developer lain.",
    "addons.4.title": "HTML ke WordPress",
    "addons.4.desc": "Template HTML statis diubah jadi tema WordPress dengan konten yang bisa Anda edit sendiri lewat dashboard.",
    "addons.5.title": "Setup Multibahasa",
    "addons.5.desc": "Pemasangan WPML atau Polylang, struktur URL per bahasa, dan penyiapan konten terjemahan.",
    "addons.6.title": "Integrasi Pihak Ketiga",
    "addons.6.desc": "Sambungkan website ke payment gateway, CRM, WhatsApp API, email marketing, atau layanan lain lewat API.",

    "stack.title": "Tech Stack",
    "stack.subtitle": "Tools yang saya gunakan sehari-hari",

    "process.title": "Cara Kerja",
    "process.subtitle": "Prosesnya simpel dan transparan",
    "process.1.title": "Konsultasi",
    "process.1.desc": "Diskusi kebutuhan, target, dan estimasi biaya & waktu.",
    "process.2.title": "Desain",
    "process.2.desc": "Mockup atau wireframe untuk disetujui sebelum coding.",
    "process.3.title": "Development",
    "process.3.desc": "Pengerjaan dengan update progres berkala.",
    "process.4.title": "Launch & Support",
    "process.4.desc": "Deploy ke hosting, training singkat, dan garansi revisi.",

    "contact.title": "Kontak",
    "contact.subtitle": "Punya project? Mari diskusikan.",
    "contact.email": "Email",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "Lokasi",
    "contact.location.value": "Indonesia (Remote)",
    "contact.hours": "Jam Kerja",
    "contact.hours.value": "Senin – Jumat, 09.00 – 18.00 WIB",

    "footer.text": "© 2026 Sayogi Creative. Dibuat dengan kopi dan kode."
  },
  "en": {
    "nav.services": "Services",
    "nav.addons": "Add-on Services",
    "nav.process": "Process",
    "nav.contact": "Contact",

    "hero.badge": "Freelance Web Developer · Indonesia",
    "hero.title": "Websites & Web Apps Built to Perform",
    "hero.subtitle": "Specializing in WordPress, WooCommerce, Elementor, and custom web applications with Laravel & CodeIgniter. From online stores to internal business systems.",
    "hero.scroll": "Scroll down",

    "services.title": "Services",
    "services.subtitle": "What I can do for your business",
    "services.1.title": "WooCommerce Online Store",
    "services.1.desc": "Complete online store with product catalog, cart, payment gateway (Stripe/PayPal/Midtrans), and shipping setup.",
    "services.2.title": "Custom WordPress Plugin",
    "services.2.desc": "Tailored plugins: API integrations, custom WooCommerce features, automation, and admin dashboards.",
    "services.3.title": "Elementor Design",
    "services.3.desc": "Landing pages and company profile websites built with Elementor. Fast, responsive, easy to edit yourself.",
    "services.4.title": "Laravel Web Application",
    "services.4.desc": "Custom systems: CRM, booking, inventory, POS, or a REST API for your mobile app.",
    "services.5.title": "CodeIgniter Web Application",
    "services.5.desc": "New development or maintenance for existing CodeIgniter 3/4 applications.",
    "services.6.title": "Maintenance & Bug Fixing",
    "services.6.desc": "Error fixes, speed optimization, security hardening, hosting migration, and routine updates.",

    "addons.title": "Add-on Services",
    "addons.subtitle": "Smaller jobs you can order on their own, no big package required",
    "addons.1.title": "Website Tweaks",
    "addons.1.desc": "Small changes to layout, colors, copy, or stubborn CSS. Billed per item, usually done the same day.",
    "addons.2.title": "Theme & Plugin Customization",
    "addons.2.desc": "Modify the theme or plugin you already run so it behaves the way you need, without breaking future updates.",
    "addons.3.title": "PSD / Figma to HTML",
    "addons.3.desc": "Turn design files into clean, responsive, pixel-accurate HTML/CSS another developer can pick up.",
    "addons.4.title": "HTML to WordPress",
    "addons.4.desc": "Convert a static HTML template into a WordPress theme with content you can edit yourself from the dashboard.",
    "addons.5.title": "Multilingual Setup",
    "addons.5.desc": "WPML or Polylang installation, per-language URL structure, and translation content setup.",
    "addons.6.title": "Third-Party Integration",
    "addons.6.desc": "Connect your site to payment gateways, CRM, WhatsApp API, email marketing, or any other service via API.",

    "stack.title": "Tech Stack",
    "stack.subtitle": "Tools I use every day",

    "process.title": "How It Works",
    "process.subtitle": "Simple and transparent process",
    "process.1.title": "Consultation",
    "process.1.desc": "Discuss requirements, goals, and estimate cost & timeline.",
    "process.2.title": "Design",
    "process.2.desc": "Mockup or wireframe for approval before coding starts.",
    "process.3.title": "Development",
    "process.3.desc": "Build with regular progress updates.",
    "process.4.title": "Launch & Support",
    "process.4.desc": "Deploy to hosting, short training, and revision guarantee.",

    "contact.title": "Contact",
    "contact.subtitle": "Have a project? Let's talk.",
    "contact.email": "Email",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "Location",
    "contact.location.value": "Indonesia (Remote)",
    "contact.hours": "Working Hours",
    "contact.hours.value": "Mon – Fri, 09:00 – 18:00 (GMT+7)",

    "footer.text": "© 2026 Sayogi Creative. Made with coffee and code."
  },
  "ja": {
    "nav.services": "サービス",
    "nav.addons": "追加サービス",
    "nav.process": "進め方",
    "nav.contact": "お問い合わせ",

    "hero.badge": "フリーランス Web デベロッパー · インドネシア",
    "hero.title": "成果につながる Web サイトと Web アプリ",
    "hero.subtitle": "WordPress、WooCommerce、Elementor、そして Laravel・CodeIgniter によるカスタム Web アプリケーションを専門としています。オンラインストアから社内業務システムまで対応します。",
    "hero.scroll": "スクロール",

    "services.title": "サービス",
    "services.subtitle": "ビジネスのためにできること",
    "services.1.title": "WooCommerce オンラインストア",
    "services.1.desc": "商品カタログ、カート、決済ゲートウェイ（Stripe/PayPal/Midtrans）、配送設定まで揃ったオンラインストアを構築します。",
    "services.2.title": "WordPress カスタムプラグイン",
    "services.2.desc": "API 連携、WooCommerce の独自機能、自動化、管理画面など、要件に合わせたプラグインを開発します。",
    "services.3.title": "Elementor デザイン",
    "services.3.desc": "Elementor で作るランディングページと会社紹介サイト。表示が速く、レスポンシブで、ご自身で編集できます。",
    "services.4.title": "Laravel Web アプリケーション",
    "services.4.desc": "CRM、予約、在庫管理、POS などの独自システム、モバイルアプリ向けの REST API も構築します。",
    "services.5.title": "CodeIgniter Web アプリケーション",
    "services.5.desc": "CodeIgniter 3/4 の新規開発、および既存アプリケーションの保守に対応します。",
    "services.6.title": "保守・不具合修正",
    "services.6.desc": "エラー修正、表示速度の改善、セキュリティ強化、サーバー移転、定期アップデートを行います。",

    "addons.title": "追加サービス",
    "addons.subtitle": "大きなパッケージなしで、単体でご依頼いただける小さな作業です",
    "addons.1.title": "サイトの微調整",
    "addons.1.desc": "レイアウト、色、文言、扱いにくい CSS の小さな修正。項目ごとのお見積りで、多くは当日中に完了します。",
    "addons.2.title": "テーマ・プラグインのカスタマイズ",
    "addons.2.desc": "現在お使いのテーマやプラグインを、今後のアップデートを壊さずに必要な動作へ変更します。",
    "addons.3.title": "PSD / Figma から HTML へ",
    "addons.3.desc": "デザインファイルを、他の開発者が引き継げる整理されたレスポンシブ HTML/CSS に変換します。",
    "addons.4.title": "HTML から WordPress へ",
    "addons.4.desc": "静的な HTML テンプレートを、管理画面から自分で編集できる WordPress テーマに変換します。",
    "addons.5.title": "多言語対応の設定",
    "addons.5.desc": "WPML または Polylang の導入、言語ごとの URL 設計、翻訳コンテンツの設定を行います。",
    "addons.6.title": "外部サービス連携",
    "addons.6.desc": "決済ゲートウェイ、CRM、WhatsApp API、メールマーケティングなど、API を通じて連携します。",

    "stack.title": "技術スタック",
    "stack.subtitle": "日常的に使っているツール",

    "process.title": "進め方",
    "process.subtitle": "シンプルで分かりやすい流れです",
    "process.1.title": "ご相談",
    "process.1.desc": "要件と目標を伺い、費用と期間をお見積りします。",
    "process.2.title": "デザイン",
    "process.2.desc": "実装前にモックアップまたはワイヤーフレームをご確認いただきます。",
    "process.3.title": "開発",
    "process.3.desc": "定期的に進捗をご報告しながら実装します。",
    "process.4.title": "公開とサポート",
    "process.4.desc": "サーバーへの公開、簡単な操作説明、修正保証をご提供します。",

    "contact.title": "お問い合わせ",
    "contact.subtitle": "プロジェクトのご相談をお待ちしています。",
    "contact.email": "メール",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "所在地",
    "contact.location.value": "インドネシア（リモート）",
    "contact.hours": "対応時間",
    "contact.hours.value": "月〜金 9:00〜18:00（GMT+7）",

    "footer.text": "© 2026 Sayogi Creative. コーヒーとコードで作りました。"
  },
  "ar": {
    "nav.services": "الخدمات",
    "nav.addons": "خدمات إضافية",
    "nav.process": "طريقة العمل",
    "nav.contact": "تواصل",

    "hero.badge": "مطوّر ويب مستقل · إندونيسيا",
    "hero.title": "مواقع وتطبيقات ويب مبنية لتحقيق النتائج",
    "hero.subtitle": "متخصص في ووردبريس وووكومرس وإليمنتور، وتطبيقات الويب المخصصة باستخدام Laravel و CodeIgniter. من المتاجر الإلكترونية إلى الأنظمة الداخلية للشركات.",
    "hero.scroll": "مرّر للأسفل",

    "services.title": "الخدمات",
    "services.subtitle": "ما الذي يمكنني تقديمه لأعمالك",
    "services.1.title": "متجر ووكومرس إلكتروني",
    "services.1.desc": "متجر إلكتروني متكامل يشمل كتالوج المنتجات وسلة الشراء وبوابات الدفع (Stripe/PayPal/Midtrans) وإعداد الشحن.",
    "services.2.title": "إضافة ووردبريس مخصصة",
    "services.2.desc": "إضافات مصممة حسب الطلب: ربط واجهات API، ميزات ووكومرس خاصة، الأتمتة، ولوحات تحكم الإدارة.",
    "services.3.title": "تصميم بإليمنتور",
    "services.3.desc": "صفحات هبوط ومواقع تعريفية مبنية بإليمنتور. سريعة، متجاوبة، ويمكنك تعديلها بنفسك.",
    "services.4.title": "تطبيق ويب بـ Laravel",
    "services.4.desc": "أنظمة مخصصة: إدارة العملاء، الحجوزات، المخزون، نقاط البيع، أو واجهة REST API لتطبيقك.",
    "services.5.title": "تطبيق ويب بـ CodeIgniter",
    "services.5.desc": "تطوير جديد أو صيانة لتطبيقات CodeIgniter 3/4 القائمة.",
    "services.6.title": "الصيانة وإصلاح الأعطال",
    "services.6.desc": "إصلاح الأخطاء، تحسين السرعة، تعزيز الأمان، نقل الاستضافة، والتحديثات الدورية.",

    "addons.title": "خدمات إضافية",
    "addons.subtitle": "أعمال صغيرة يمكن طلبها بشكل منفصل، دون الحاجة إلى باقة كاملة",
    "addons.1.title": "تعديلات سريعة على الموقع",
    "addons.1.desc": "تغييرات صغيرة في التخطيط أو الألوان أو النصوص أو CSS العنيد. تُحتسب لكل بند، وتُنجز عادة في اليوم نفسه.",
    "addons.2.title": "تخصيص القوالب والإضافات",
    "addons.2.desc": "تعديل القالب أو الإضافة التي تستخدمها لتعمل كما تحتاج، دون تعطيل التحديثات المستقبلية.",
    "addons.3.title": "من PSD / Figma إلى HTML",
    "addons.3.desc": "تحويل ملفات التصميم إلى HTML/CSS نظيف ومتجاوب ودقيق يمكن لمطوّر آخر متابعته.",
    "addons.4.title": "من HTML إلى ووردبريس",
    "addons.4.desc": "تحويل قالب HTML ثابت إلى قالب ووردبريس بمحتوى يمكنك تعديله بنفسك من لوحة التحكم.",
    "addons.5.title": "إعداد تعدد اللغات",
    "addons.5.desc": "تثبيت WPML أو Polylang، وبنية روابط لكل لغة، وإعداد محتوى الترجمة.",
    "addons.6.title": "الربط مع خدمات خارجية",
    "addons.6.desc": "ربط موقعك ببوابات الدفع، أنظمة إدارة العملاء، واتساب API، التسويق بالبريد، أو أي خدمة أخرى عبر API.",

    "stack.title": "التقنيات المستخدمة",
    "stack.subtitle": "الأدوات التي أعمل بها يوميًا",

    "process.title": "طريقة العمل",
    "process.subtitle": "خطوات بسيطة وواضحة",
    "process.1.title": "الاستشارة",
    "process.1.desc": "مناقشة المتطلبات والأهداف مع تقدير التكلفة والمدة.",
    "process.2.title": "التصميم",
    "process.2.desc": "نموذج أولي أو مخطط للموافقة عليه قبل بدء البرمجة.",
    "process.3.title": "التطوير",
    "process.3.desc": "التنفيذ مع تحديثات دورية عن سير العمل.",
    "process.4.title": "الإطلاق والدعم",
    "process.4.desc": "النشر على الاستضافة، تدريب مختصر، وضمان التعديلات.",

    "contact.title": "تواصل",
    "contact.subtitle": "لديك مشروع؟ لنتحدث.",
    "contact.email": "البريد الإلكتروني",
    "contact.whatsapp": "واتساب",
    "contact.location": "الموقع",
    "contact.location.value": "إندونيسيا (عن بُعد)",
    "contact.hours": "ساعات العمل",
    "contact.hours.value": "الاثنين – الجمعة، 09:00 – 18:00 (GMT+7)",

    "footer.text": "© 2026 Sayogi Creative. صُنع بالقهوة والشيفرة."
  },
  "zh": {
    "nav.services": "服务",
    "nav.addons": "附加服务",
    "nav.process": "合作流程",
    "nav.contact": "联系",

    "hero.badge": "自由 Web 开发者 · 印度尼西亚",
    "hero.title": "为业务增长而生的网站与 Web 应用",
    "hero.subtitle": "专注 WordPress、WooCommerce、Elementor，以及基于 Laravel 与 CodeIgniter 的定制 Web 应用。从线上商城到企业内部系统。",
    "hero.scroll": "向下滚动",

    "services.title": "服务",
    "services.subtitle": "我能为你的业务做什么",
    "services.1.title": "WooCommerce 在线商城",
    "services.1.desc": "完整的在线商城，包含商品目录、购物车、支付网关（Stripe/PayPal/Midtrans）与运费设置。",
    "services.2.title": "WordPress 定制插件",
    "services.2.desc": "按需开发插件：API 对接、WooCommerce 定制功能、自动化流程与后台管理面板。",
    "services.3.title": "Elementor 设计",
    "services.3.desc": "使用 Elementor 制作落地页与企业官网。加载快、自适应，你可以自行编辑。",
    "services.4.title": "Laravel Web 应用",
    "services.4.desc": "定制系统：CRM、预约、库存、POS，或为移动端提供 REST API。",
    "services.5.title": "CodeIgniter Web 应用",
    "services.5.desc": "CodeIgniter 3/4 的全新开发，或现有应用的维护。",
    "services.6.title": "维护与故障修复",
    "services.6.desc": "修复报错、优化速度、加固安全、迁移主机与日常更新。",

    "addons.title": "附加服务",
    "addons.subtitle": "可以单独下单的小项目，无需购买整套方案",
    "addons.1.title": "网站微调",
    "addons.1.desc": "布局、配色、文案或顽固 CSS 的小改动。按项计费，通常当天完成。",
    "addons.2.title": "主题与插件定制",
    "addons.2.desc": "改造你正在使用的主题或插件，使其符合需求，同时不影响后续更新。",
    "addons.3.title": "PSD / Figma 转 HTML",
    "addons.3.desc": "将设计稿转成结构清晰、自适应、还原度高的 HTML/CSS，方便其他开发者接手。",
    "addons.4.title": "HTML 转 WordPress",
    "addons.4.desc": "把静态 HTML 模板转为 WordPress 主题，内容可在后台自行编辑。",
    "addons.5.title": "多语言配置",
    "addons.5.desc": "安装 WPML 或 Polylang，规划各语言的 URL 结构，并配置翻译内容。",
    "addons.6.title": "第三方对接",
    "addons.6.desc": "通过 API 将网站接入支付网关、CRM、WhatsApp API、邮件营销或其他服务。",

    "stack.title": "技术栈",
    "stack.subtitle": "我每天使用的工具",

    "process.title": "合作流程",
    "process.subtitle": "流程简单、过程透明",
    "process.1.title": "沟通需求",
    "process.1.desc": "了解需求与目标，并给出费用与周期评估。",
    "process.2.title": "设计",
    "process.2.desc": "先确认原型或线框图，再开始编码。",
    "process.3.title": "开发",
    "process.3.desc": "按进度定期同步开发进展。",
    "process.4.title": "上线与支持",
    "process.4.desc": "部署到主机、简短培训，并提供修改保障。",

    "contact.title": "联系",
    "contact.subtitle": "有项目想做？聊聊吧。",
    "contact.email": "邮箱",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "所在地",
    "contact.location.value": "印度尼西亚（远程）",
    "contact.hours": "工作时间",
    "contact.hours.value": "周一至周五 09:00 – 18:00（GMT+7）",

    "footer.text": "© 2026 Sayogi Creative. 用咖啡和代码打造。"
  }
}
;
