const LOCALES = {
  "id": { "name": "Bahasa Indonesia", "flag": "id" },
  "en": { "name": "English", "flag": "gb" }
};

const LANG = {
  "id": {
    "nav.services": "Layanan",
    "nav.addons": "Layanan Tambahan",
    "nav.process": "Proses",
    "nav.contact": "Kontak",

    "hero.badge": "Freelance Web Developer · Indonesia",
    "hero.title": "Website & Aplikasi Web yang Siap Menghasilkan",
    "hero.subtitle": "Spesialis WordPress, WooCommerce, Elementor, dan aplikasi web custom dengan Laravel & CodeIgniter. Dari toko online sampai sistem internal bisnis.",
    "hero.cta1": "Lihat Layanan",
    "hero.cta2": "Hubungi Saya",

    "services.title": "Layanan",
    "services.subtitle": "Apa yang bisa saya kerjakan untuk bisnis Anda",
    "services.1.title": "Toko Online WooCommerce",
    "services.1.desc": "Toko online lengkap dengan katalog produk, keranjang, payment gateway (Midtrans/Xendit/Stripe), dan pengaturan ongkir.",
    "services.2.title": "Custom WordPress Plugin",
    "services.2.desc": "Plugin khusus sesuai kebutuhan: integrasi API, fitur custom WooCommerce, otomasi, dan dashboard admin.",
    "services.3.title": "Desain Elementor",
    "services.3.desc": "Landing page dan website company profile berbasis Elementor, cepat, responsif, dan mudah Anda edit sendiri.",
    "services.4.title": "Aplikasi Web Laravel",
    "services.4.desc": "Sistem custom: CRM, booking, inventory, POS, atau REST API untuk aplikasi mobile Anda.",
    "services.5.title": "Aplikasi Web CodeIgniter",
    "services.5.desc": "Pengembangan baru atau maintenance aplikasi CodeIgniter 3/4 yang sudah berjalan.",
    "services.6.title": "Maintenance & Perbaikan",
    "services.6.desc": "Perbaikan error, optimasi kecepatan, keamanan, migrasi hosting, dan update rutin.",

    "addons.title": "Layanan Tambahan",
    "addons.subtitle": "Pekerjaan berskala kecil yang bisa dipesan satuan, tanpa paket besar",
    "addons.1.title": "Website Tweaks",
    "addons.1.desc": "Perubahan kecil pada layout, warna, teks, atau CSS yang bandel. Dihitung per item dan biasanya selesai di hari yang sama.",
    "addons.2.title": "Kustomisasi Tema & Plugin",
    "addons.2.desc": "Modifikasi tema atau plugin yang sudah Anda pakai agar berperilaku sesuai kebutuhan, tanpa bikin update berikutnya rusak.",
    "addons.3.title": "PSD / Figma ke HTML",
    "addons.3.desc": "Konversi file desain jadi HTML/CSS responsif yang rapi, presisi, dan siap dilanjutkan developer lain.",
    "addons.4.title": "HTML ke WordPress",
    "addons.4.desc": "Template HTML statis diubah jadi tema WordPress dengan konten yang bisa Anda edit sendiri lewat dashboard.",
    "addons.5.title": "Setup Multibahasa",
    "addons.5.desc": "Pemasangan WPML atau Polylang, struktur URL per bahasa, dan penyiapan konten terjemahan.",
    "addons.6.title": "Integrasi Pihak Ketiga",
    "addons.6.desc": "Sambungkan website ke payment gateway, CRM, WhatsApp API, email marketing, atau layanan lain lewat API.",

    "stack.title": "Tech Stack",
    "stack.subtitle": "Tools yang saya gunakan sehari-hari",

    "process.title": "Cara Kerja",
    "process.subtitle": "Prosesnya simpel dan transparan",
    "process.1.title": "Konsultasi",
    "process.1.desc": "Diskusi kebutuhan, target, dan estimasi biaya & waktu.",
    "process.2.title": "Desain",
    "process.2.desc": "Mockup atau wireframe untuk disetujui sebelum coding.",
    "process.3.title": "Development",
    "process.3.desc": "Pengerjaan dengan update progres berkala.",
    "process.4.title": "Launch & Support",
    "process.4.desc": "Deploy ke hosting, training singkat, dan garansi revisi.",

    "contact.title": "Kontak",
    "contact.subtitle": "Punya project? Mari diskusikan.",
    "contact.email": "Email",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "Lokasi",
    "contact.location.value": "Indonesia (Remote)",
    "contact.hours": "Jam Kerja",
    "contact.hours.value": "Senin – Jumat, 09.00 – 18.00 WIB",

    "footer.text": "© 2026 Sayogi Creative. Dibuat dengan kopi dan kode."
  },
  "en": {
    "nav.services": "Services",
    "nav.addons": "Add-on Services",
    "nav.process": "Process",
    "nav.contact": "Contact",

    "hero.badge": "Freelance Web Developer · Indonesia",
    "hero.title": "Websites & Web Apps Built to Perform",
    "hero.subtitle": "Specializing in WordPress, WooCommerce, Elementor, and custom web applications with Laravel & CodeIgniter. From online stores to internal business systems.",
    "hero.cta1": "View Services",
    "hero.cta2": "Get in Touch",

    "services.title": "Services",
    "services.subtitle": "What I can do for your business",
    "services.1.title": "WooCommerce Online Store",
    "services.1.desc": "Complete online store with product catalog, cart, payment gateway (Stripe/PayPal/Midtrans), and shipping setup.",
    "services.2.title": "Custom WordPress Plugin",
    "services.2.desc": "Tailored plugins: API integrations, custom WooCommerce features, automation, and admin dashboards.",
    "services.3.title": "Elementor Design",
    "services.3.desc": "Landing pages and company profile websites built with Elementor. Fast, responsive, easy to edit yourself.",
    "services.4.title": "Laravel Web Application",
    "services.4.desc": "Custom systems: CRM, booking, inventory, POS, or a REST API for your mobile app.",
    "services.5.title": "CodeIgniter Web Application",
    "services.5.desc": "New development or maintenance for existing CodeIgniter 3/4 applications.",
    "services.6.title": "Maintenance & Bug Fixing",
    "services.6.desc": "Error fixes, speed optimization, security hardening, hosting migration, and routine updates.",

    "addons.title": "Add-on Services",
    "addons.subtitle": "Smaller jobs you can order on their own, no big package required",
    "addons.1.title": "Website Tweaks",
    "addons.1.desc": "Small changes to layout, colors, copy, or stubborn CSS. Billed per item, usually done the same day.",
    "addons.2.title": "Theme & Plugin Customization",
    "addons.2.desc": "Modify the theme or plugin you already run so it behaves the way you need, without breaking future updates.",
    "addons.3.title": "PSD / Figma to HTML",
    "addons.3.desc": "Turn design files into clean, responsive, pixel-accurate HTML/CSS another developer can pick up.",
    "addons.4.title": "HTML to WordPress",
    "addons.4.desc": "Convert a static HTML template into a WordPress theme with content you can edit yourself from the dashboard.",
    "addons.5.title": "Multilingual Setup",
    "addons.5.desc": "WPML or Polylang installation, per-language URL structure, and translation content setup.",
    "addons.6.title": "Third-Party Integration",
    "addons.6.desc": "Connect your site to payment gateways, CRM, WhatsApp API, email marketing, or any other service via API.",

    "stack.title": "Tech Stack",
    "stack.subtitle": "Tools I use every day",

    "process.title": "How It Works",
    "process.subtitle": "Simple and transparent process",
    "process.1.title": "Consultation",
    "process.1.desc": "Discuss requirements, goals, and estimate cost & timeline.",
    "process.2.title": "Design",
    "process.2.desc": "Mockup or wireframe for approval before coding starts.",
    "process.3.title": "Development",
    "process.3.desc": "Build with regular progress updates.",
    "process.4.title": "Launch & Support",
    "process.4.desc": "Deploy to hosting, short training, and revision guarantee.",

    "contact.title": "Contact",
    "contact.subtitle": "Have a project? Let's talk.",
    "contact.email": "Email",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "Location",
    "contact.location.value": "Indonesia (Remote)",
    "contact.hours": "Working Hours",
    "contact.hours.value": "Mon – Fri, 09:00 – 18:00 (GMT+7)",

    "footer.text": "© 2026 Sayogi Creative. Made with coffee and code."
  }
}
;
